[package]
name = "tic_tac_toe_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.5"
lazy_static = "1.5.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = "1.0.204"
