FROM node:20-alpine AS frontend-builder

WORKDIR /frontend

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install

COPY frontend/ ./
RUN npm run build

FROM rust:latest AS builder

WORKDIR /app

RUN apt update && apt -y install musl-tools &&\
    rustup target add x86_64-unknown-linux-musl

COPY Cargo.toml Cargo.lock Makefile ./
COPY assets assets
COPY src src

COPY --from=frontend-builder /frontend/dist/index.html /app/assets/index.html

RUN make build BUILD_TYPE=release TARGET=x86_64-unknown-linux-musl &&\
    mkdir /app/build/store

FROM ubuntu:latest

COPY --from=builder /app/build /app

RUN apt update && apt -y install autossh &&\
    useradd -m user &&\
    mkdir -p /home/user/.ssh &&\
    chown -R user:user /home/user/.ssh

COPY ./certs  /home/user/.ssh
RUN chmod 666 /home/user/.ssh/id_ed25519 &&\
    echo "Host serveo.net\n\tIdentityFile /home/user/.ssh/id_ed25519\n" >> /home/user/.ssh/config

COPY scripts/entrypoint.sh /app/

USER user

CMD ["sh", "/app/entrypoint.sh"]
